apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  labels:
    app: rsapp
  name: set1
spec:
  replicas: 2     
  selector: 
    matchLabels:
      app: rsapp
  template: 
    metadata:
     labels: 
       app: rsapp
    spec:
      containers:
        - name: cont1
          image: nginx      
